apiVersion: v1
kind: Service
metadata:
  name: partner-django-admin
  labels:
    app.kubernetes.io/name: partner-django-admin
spec:
  ports:
  - port: 8000
    name: http  
    targetPort: 8000
    nodePort: 30012
  selector:
    app.kubernetes.io/name: partner-django-admin
  type: NodePort