apiVersion: v1
kind: Service
metadata:
    name: sc-ins-stage
    labels:
      app.kubernetes.io/name: sc-ins-stage
spec:
  ports:
  - port: 8083
    name: http  
    targetPort: 8083
    nodePort: 30390
  selector:
    app.kubernetes.io/name: sc-ins-stage
  type: NodePort