apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - name: debug
      port: 8989
      targetPort: 8989
      protocol: TCP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}