apiVersion: v1
kind: Service
metadata:
  name: venue-partner-user
  labels:
    app.kubernetes.io/name: venue-partner-user
spec:
  ports:
  - port: 8080
    name: http  
    targetPort: 8080
    nodePort: 30162
  selector:
    app.kubernetes.io/name: venue-partner-user
  type: NodePort