apiVersion: v1
kind: Service
metadata:
  name: micro-beacon-service
  labels:
    app.kubernetes.io/name: micro-beacon-service
spec:
  ports:
    - port: 8879
      name: http
      targetPort: 8879
      nodePort: 30031
  selector:
    app.kubernetes.io/name: micro-beacon-service
  type: NodePort
