apiVersion: v1
kind: Service
metadata:
    name: cloud-gateway-stage
    labels:
      app.kubernetes.io/name: cloud-gateway-stage
spec:
  ports:
  - port: 8088
    name: http  
    targetPort: 8088
    nodePort: 30561
  selector:
    app.kubernetes.io/name: cloud-gateway-stage
  type: NodePort