apiVersion: v1
kind: Service
metadata:
    name: venue-partner-admin-stage
    labels:
      app.kubernetes.io/name: venue-partner-admin-stage
spec:
  ports:
  - port: 8080
    name: http  
    targetPort: 8080
    nodePort: 30140
  selector:
    app.kubernetes.io/name: venue-partner-admin-stage
  type: NodePort
