apiVersion: apps/v1
kind: Deployment
metadata:
  name: venue-admin-partner
spec:
  replicas: 0
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: venue-admin-partner
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: venue-admin-partner
        version: v1.0
        app.kubernetes.io/name: venue-admin-partner
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - venue-admin-partner
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: app
          image: 222222222222.dkr.ecr.ap-northeast-2.amazonaws.com/venue-admin-partner-prod
          ports:
            - containerPort: 8055
          readinessProbe:
            httpGet:
              path: /partner/
              port: 8055
            initialDelaySeconds: 30
            periodSeconds: 5
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
