apiVersion: v1
kind: Service
metadata:
  name: venue-admin-partner
  labels:
    app.kubernetes.io/name: venue-admin-partner
spec:
  ports:
    - port: 8055
      name: http
      targetPort: 8055
      nodePort: 30144
  selector:
    app.kubernetes.io/name: venue-admin-partner
  type: NodePort
