apiVersion: v1
kind: Service
metadata:
    name: partner-django-admin-dev
    labels:
      app.kubernetes.io/name: partner-django-admin-dev
spec:
  ports:
  - port: 8000
    name: http  
    targetPort: 8000
    nodePort: 30010
  selector:
    app.kubernetes.io/name: partner-django-admin-dev
  type: NodePort