apiVersion: v1
kind: Service
metadata:
    name: health-backend
    labels:
      app.kubernetes.io/name: health-backend
spec:
  ports:
  - port: 8001
    name: http  
    targetPort: 8001
    nodePort: 30210
  selector:
    app.kubernetes.io/name: health-backend
  type: NodePort