apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-studio-fastapi-dev
spec:
  replicas: 0
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-studio-fastapi-dev
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-studio-fastapi-dev
    spec:
      containers:
        - name: app
          image: 111111111111.dkr.ecr.ap-northeast-2.amazonaws.com/ai-studio-fastapi-dev
          resources: {}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          env:
            - name: ENV
              value: dev
