apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmemall-backend-prod
spec:
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: acmemall-backend-prod
  strategy:
      type: RollingUpdate
  template:
    metadata:
      annotations:
        ad.datadoghq.com/acmemall-backend-prod.logs: '[{"source":"django"}]'
      labels: 
        app.kubernetes.io/name: acmemall-backend-prod
    spec:
      tolerations:
      - key: node-group-type
        operator: Equal
        value: mall
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-group-type
                operator: In
                values:
                - mall  
      containers:
      - name: acmemall-backend-prod
        image: 222222222222.dkr.ecr.ap-northeast-2.amazonaws.com/acmemall-backend-prod
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: 7
          limits:
            cpu: 7
        readinessProbe:
          httpGet:
            path: /ht/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 15
        command: [ "/bin/bash","-c","python manage.py create_server_config && gunicorn acme.wsgi:application --bind 0.0.0.0:8000 --max-requests 1000 --max-requests-jitter 150 --worker-connections=12 --worker-class=gevent --workers=15 --timeout 120 --access-logfile None --error-logfile - --log-level warning " ]
        env:
          - name: AWS_DEFAULT_REGION
            value: ap-northeast-2
          - name: CELERY_BROKER_URL
            value: redis://acmemall-prod-cache.abcdef.ng.0001.apn2.cache.amazonaws.com:6379/2
          - name: DJANGO_SETTINGS_MODULE
            value: acme.settings.prod
          - name: ACME_ENV
            value: prod
          - name: REDIS_CACHE_URL
            value: redis://acmemall-prod-cache.abcdef.ng.0001.apn2.cache.amazonaws.com:6379/0
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: partner-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: partner-secret
                key: AWS_SECRET_ACCESS_KEY
          # DD ENV
          - name: DD_ENV
            value: prod
          - name: DD_SERVICE
            value: mall-backend
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_VERSION
            value: "1"
          - name: DD_DJANGO_INSTRUMENT_DATABASES
            value: "false"
      terminationGracePeriodSeconds: 60