apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: acmemall-backend-prod-worker
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: acmemall-backend-prod-worker
  minReplicas: 8
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
