resources:
- deployment.yml
- service.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /venue-partner-user-dev
  newTag: "819"
- name: 111111111111.dkr.ecr.ap-northeast-2.amazonaws.com/venue-partner-user-dev
  newTag: "801"
