apiVersion: v1
kind: Service
metadata:
    name: venue-partner-user-dev
    labels:
      app.kubernetes.io/name: venue-partner-user-dev
spec:
  ports:
  - port: 8080
    name: http  
    targetPort: 8080
    nodePort: 30160
  selector:
    app.kubernetes.io/name: venue-partner-user-dev
  type: NodePort