apiVersion: v1
kind: Service
metadata:
  name: play-service-dev
  labels:
    app.kubernetes.io/name: play-service-dev
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8081
      nodePort: 30033
  selector:
    app.kubernetes.io/name: play-service-dev
  type: NodePort
