apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro-beacon-service-dev
spec:
  destination:
    name: micro-beacon-service-dev
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: micro-beacon-service/dev
    repoURL: 'git@github.com:AcmeCorp/manifest-k8s-acme-cluster.git'
    targetRevision: HEAD
  project: default
