apiVersion: v1
kind: Service
metadata:
  name: common-user-service-dev
  labels:
    app.kubernetes.io/name: common-user-service-dev
spec:
  ports:
    - port: 8871
      name: http
      targetPort: 8871
      nodePort: 30734
  selector:
    app.kubernetes.io/name: common-user-service-dev
  type: NodePort
