apiVersion: v1
kind: Service
metadata:
  name: acmemall-backend-stage
  labels:
    app.kubernetes.io/name: acmemall-backend-stage
spec:
  ports:
    - port: 8000
      name: http
      targetPort: 8000
      nodePort: 30061
  selector:
    app.kubernetes.io/name: acmemall-backend-stage
  type: NodePort
