apiVersion: v1
kind: Service
metadata:
  name: micro-user-service
  labels:
    app.kubernetes.io/name: micro-user-service
spec:
  ports:
    - port: 8871
      name: http
      targetPort: 8871
      nodePort: 30732
  selector:
    app.kubernetes.io/name: micro-user-service
  type: NodePort
