resources:
- deployment.yml
- service.yml
apiVersion: kustomize.config.k8s.io/v1beta1
# namespace: health
kind: Kustomization
images:
- name: /play-service-prod
  newTag: "90"
- name: 222222222222.dkr.ecr.ap-northeast-2.amazonaws.com/play-service-prod
  newTag: "83"
